### ISSUE TITLE
Option to set up custom redirect URL

### ISSUE THREAD

**Issue by astridjerald** [labd/django-session-timeout#7]
hey there, 
A user of django-session-timeout here. I was wondering if I could modify the url that my django app goes to after logout, since the current automatic redirect url is an invalid one.

**Comment by fabiomarsala** [comment]
Hi , 
I have actually bypass the issue by editing 

lib/python3.6/site-packages/django_session_timeout/middleware.py

![CustomViewRedirect](https://user-images.githubusercontent.com/23101916/65811861-f20df380-e173-11e9-9c52-dba0026e1d16.jpg)

**Comment by astridjerald** [comment]
Neat trick, fabiomarsala.

**Comment by millerthegorilla** [comment]
Can this be added as a feature request?

**Comment by millerthegorilla** [comment]
I've edited the code to check for a constant in settings that refers to a custom session redirect url, and uses the above code, effectively, or uses the original, if no constant is defined.

**Comment by mvantellingen** [comment]
Thanks, see daa75f6c622feb0495384e53eefb109a920ac4fc
